name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Instance 1
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 54.88.130.216
        username: ec2-user
        key: ${{ secrets.HTML_BALANCER }}
        script: |
          cd /var/www/html
          git pull

    - name: Deploy to Instance 2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 34.207.92.31
        username: ec2-user
        key: ${{ secrets.HTML_BALANCER }}
        script: |
          cd /var/www/html
          git pull
