name: Deploy to EC2 Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las instancias EC2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HTML_BALANCER }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.88.130.216 >> ~/.ssh/known_hosts
          ssh-keyscan -H 34.207.92.31 >> ~/.ssh/known_hosts

            # Paso 3: Desplegar los archivos a la primera instancia EC2
      - name: Deploy to Instance 1
        run: |
          ssh -T -o StrictHostKeyChecking=no ec2-user@54.88.130.216 << 'EOF'
            cd /var/www/html
            git pull origin main  # Actualizar los archivos del repositorio
            sudo systemctl restart httpd  # Reiniciar Apache HTTPD
          EOF

      # Paso 4: Desplegar los archivos a la segunda instancia EC2
      - name: Deploy to Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@34.207.92.31 << 'EOF'
            cd /var/www/html
            git pull origin main  # Actualizar los archivos del repositorio
            sudo systemctl restart httpd  # Reiniciar Apache HTTPD
          EOF
