name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar la clave SSH para conectar con las instancias
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HTML-BALANCER }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 98.81.87.44 >> ~/.ssh/known_hosts
          ssh-keyscan -H 3.83.90.157 >> ~/.ssh/known_hosts

      # Paso 3: Desplegar los archivos a la primera instancia EC2
      - name: Deploy to EC2 Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@98.81.87.44 << 'EOF'
            cd /home/ec2-user/Html-Balance
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo systemctl restart httpd
          EOF

      # Paso 4: Desplegar los archivos a la segunda instancia EC2
      - name: Deploy to EC2 Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.83.90.157 << 'EOF'
            cd /home/ec2-user/Html-Balance
            git pull origin main
            sudo cp index.html /var/www/html/
            sudo systemctl restart httpd
          EOF
